import { mkdirSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const frontend = fileURLToPath(new URL('../', import.meta.url));
const raw = (process.env.BACKEND_URL ?? '').trim();
let backendUrl = '';
if (raw) {
  const url = new URL(raw);
  if (
    url.protocol !== 'https:' ||
    url.username ||
    url.password ||
    url.pathname !== '/' ||
    url.search ||
    url.hash ||
    ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname)
  ) {
    throw new Error(
      'BACKEND_URL must be a public HTTPS origin, without credentials, path, query, or fragment.',
    );
  }
  backendUrl = url.origin;
} else {
  console.warn(
    'BACKEND_URL is not set: deploying the frontend only. Login and online games need a backend.',
  );
}

mkdirSync(new URL('../src/environments/', import.meta.url), { recursive: true });
writeFileSync(
  new URL('../src/environments/environment.vercel.ts', import.meta.url),
  `// Generated by scripts/build-vercel.mjs. Contains only public configuration.\nexport const environment = ${JSON.stringify({ backendUrl, hosted: true }, null, 2)};\n`,
);

const result = spawnSync(
  process.execPath,
  ['node_modules/@angular/cli/bin/ng.js', 'build', '--configuration', 'production,vercel'],
  { cwd: frontend, stdio: 'inherit' },
);
if (result.error) throw result.error;
process.exit(result.status ?? 1);
